---
title: "git_01"
author: "veronica gonzalez"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
How doth the little crocodile   
Improve his shining tail,   
And pour the waters of the Nile.  
On every golden scale!   
How cheerfully he seem to grin,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,    
Some say in ice.     
From what I’ve tasted of desire.  
I hold with those who favor fire.   
But if it had to perish twice,   

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,     
Shining with all his might:    
He did his very best to make   
The billows smooth and bright    
And this was odd, because it was   
The middle of the night.    
                        
The moon was shining sulkily,    
Because she thought the sun    
Had got no business to be there   
After the day was done      
“It’s very rude of him,” she said,    
“To come and spoil the fun!”     

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Faith is the light of the next step   
Illuminating a way ahead,       
Without revealing the direction.    
Faith will sustain, and comfort      
Through our darkest hours.       
Faith upholds the unseen hope,        
It is the seasoning that endures,      
the pain of life whilst revealing      